name: Node.js Publish to GitHub Packages
on:
  workflow_dispatch:  # Manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        # Switch registry to GitHub Packages
        registry-url: 'https://npm.pkg.github.com'
        # Specify the scope for GitHub packages
        scope: '@${{ github.repository_owner }}'
    - run: npm ci
    - run: npm publish
      env:
        # GitHub token instead of NPM token
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}